services:
  - type: web
    name: online-edu-backend
    runtime: python
    buildCommand: "./backend/scripts/render_build.sh"
    startCommand: "cd backend && gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: online-edu-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings.production"
      - key: ALLOWED_HOSTS
        value: "online-education-platform-tdc4.onrender.com,bangladeshbravoacademy.vercel.app"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://bangladeshbravoacademy.vercel.app"

databases:
  - name: online-edu-db
    plan: free
